### PR TITLE
Designing the mobile view #67

### PR DESCRIPTION
**Pull request by adityabisoyi**
Fixes issue designing the mobile view #67

### CODE REVIEW

**Comment by AyushSarode** [comment]
Great work!

**Comment by adityabisoyi** [comment]
@AyushSarode Thanks, are you going to merge this PR?

**Comment by AyushSarode** [comment]
Great Work!

**Comment by adityabisoyi** [comment]
Please add hacktoberfest-accepted label to the PR.

**Comment by AyushSarode** [comment]
> Please add hacktoberfest-accepted label to the PR.

Both Hacktoberfest and hacktoberfest-accepted labels recognize for Contest.
Don't worry

**Pull request merged**
