### PR TITLE
Improved the Footer

### PR DESCRIPTION
**Pull request by Lo-rraine**

### CODE REVIEW

**Comment by Lo-rraine** [comment]
Hey @AyushSarode I made the PR but I see there are some conflicts.  I tried to merge the main branch into mine (footerBranch) but it tells me I cannot merge. Please advise what I should do. I'll stay online till

**Comment by AyushSarode** [comment]
> Hey @AyushSarode I made the PR but I see there are some conflicts. I tried to merge the main branch into mine (footerBranch) but it tells me I cannot merge. Please advise what I should do. I'll stay online till

Sure I'll help you with that. Remove '''<<<<<<<''' footerBranch and '''>>>>>>> main'''
We both have access to do that but for practicing stuff, work on it!

**Comment by AyushSarode** [comment]
> > Hey @AyushSarode I made the PR but I see there are some conflicts. I tried to merge the main branch into mine (footerBranch) but it tells me I cannot merge. Please advise what I should do. I'll stay online till
> 
> Sure I'll help you with that. Remove '''<<<<<<<''' footerBranch and '''>>>>>>> main''' We both have access to do that but for practicing stuff, work on it!



> > Hey @AyushSarode I made the PR but I see there are some conflicts. I tried to merge the main branch into mine (footerBranch) but it tells me I cannot merge. Please advise what I should do. I'll stay online till
> 
> Sure I'll help you with that. Remove ''' <<<<<<< ''' footerBranch and ''' >>>>>>> main ''' We both have access to do that but for practicing stuff, work on it!

**Comment by AyushSarode** [comment]
> > Hey @AyushSarode I made the PR but I see there are some conflicts. I tried to merge the main branch into mine (footerBranch) but it tells me I cannot merge. Please advise what I should do. I'll stay online till
> 
> Sure I'll help you with that. Remove <<<<<<< footerBranch and >>>>>>> main We both have access to do that but for practicing stuff, work on it!

Also If you want to work on issue #12 , I'll assign you and unassign you is currently assign

**Comment by AyushSarode** [comment]
> 



> > Hey @AyushSarode I made the PR but I see there are some conflicts. I tried to merge the main branch into mine (footerBranch) but it tells me I cannot merge. Please advise what I should do. I'll stay online till
> 
> Sure I'll help you with that. Remove <<<<<<< footerBranch and >>>>>>> main We both have access to do that but for practicing stuff, You must work on it! or if you want me to do this me, ask me!

**Comment by AyushSarode** [comment]
Hey @Lo-rraine! Can you fix this:
Screenshot (1)

I don't want blue hover when I hover at navigation buttons

**Comment by Lo-rraine** [comment]
@AyushSarode can you add the Hactoberaccepted label on my PR

image

**Comment by Lo-rraine** [comment]
> Hey @Lo-rraine! Can you fix this: Screenshot (1)
> 
> I don't want blue hover when I hover at navigation buttons

Yeah I'll take this issue

**Comment by AyushSarode** [comment]
> @AyushSarode can you add the Hactoberaccepted label on my PR
> 
> image

I labelled it, It will change in some time

**Pull request merged**
