### PR TITLE
added searchbar

### PR DESCRIPTION
**Pull request by devhabeeblateef**
Search bar issue opened, and search bar added.

### CODE REVIEW

**Comment by devhabeeblateef** [comment]
Can you please add the Hacktoberfest label to this repo

**Comment by AyushSarode** [comment]
Search icon is not working.

**Comment by devhabeeblateef** [comment]
fixed

**Comment by AyushSarode** [comment]
not showing

**Comment by devhabeeblateef** [comment]
> not showing
Please accept the new pull request, it's been fixed there

**Comment by AyushSarode** [comment]
I need to close this PR as I changed some files in this repo

**Pull request closed without merging**
