### PR TITLE
Redesigned the whole website

### PR DESCRIPTION
**Pull request by zugzwang03**
resolved issue #49 

Screenshots:

already shared in issue #49

### CODE REVIEW

**Comment by zugzwang03** [comment]
@AyushSarode

**Comment by AyushSarode** [comment]
Good work!

**Comment by zugzwang03** [comment]
@AyushSarode I am extremely sorry to inform you that your repo is presently not participating in hacktoberfest. Maintainers need to add the tag "hacktoberfest" in order to participate in it.

hacll

**Comment by AyushSarode** [comment]
> @AyushSarode I am extremely sorry to inform you that your repo is presently not participating in hacktoberfest. Maintainers need to add the tag "hacktoberfest" in order to participate in it.
> 
> hacll

I am sorry!
I forgot to add that label.
I did. After no time it will change

**Comment by zugzwang03** [comment]
> > @AyushSarode I am extremely sorry to inform you that your repo is presently not participating in hacktoberfest. Maintainers need to add the tag "hacktoberfest" in order to participate in it.
> > hacll
> 
> I am sorry! I forgot to add that label. I did. After no time it will change

yeah it is, thanks :)

**Comment by AyushSarode** [comment]
> > > @AyushSarode I am extremely sorry to inform you that your repo is presently not participating in hacktoberfest. Maintainers need to add the tag "hacktoberfest" in order to participate in it.
> > > hacll
> > 
> > 
> > I am sorry! I forgot to add that label. I did. After no time it will change
> 
> yeah it is, thanks :)

Can you send me ss?

**Comment by zugzwang03** [comment]
Screenshot_20221019-231230_Chrome

**Comment by AyushSarode** [comment]
> Screenshot_20221019-231230_Chrome
ah Thank you!

**Pull request merged**
