### PR TITLE
fix: Fix sidebar and add icon in scroll button

### PR DESCRIPTION
**Pull request by Joshua-Nweze**
Sidebar was fixed by reducing the position right value.
Bootstrap icon was used in adding scroll up button.

### CODE REVIEW

**Comment by Joshua-Nweze** [comment]
Sure

**Comment by AyushSarode** [comment]
One think that scroll up button should not be visible in the starting of the page, when you scroll a bit then it should be.
Can you fix that?

**Comment by Joshua-Nweze** [comment]
> One think that scroll up button should not be visible in the starting of the page, when you scroll a bit then it should be. Can you fix that?

Yes, that's a good idea, I will get that done

**Comment by AyushSarode** [comment]
> > One think that scroll up button should not be visible in the starting of the page, when you scroll a bit then it should be. Can you fix that?
> 
> Yes, that's a good idea, I will get that done

Amazing man! 
Thanks a lot

**Comment by AyushSarode** [comment]
I'm merging this file, till then keep working on scroll up button

**Pull request merged**
