### PR TITLE
Designed the Scrollbar

### PR DESCRIPTION
**Pull request by zugzwang03**
resolved issue #64 

Screenshots :
scroll

### CODE REVIEW

**Comment by AyushSarode** [comment]
Change that color to white. Also increase the wight of scroll-line
change

**Comment by zugzwang03** [comment]
Okay will do tomorrow

**Comment by AyushSarode** [comment]
Sure

**Comment by zugzwang03** [comment]
scroll
How is this?

**Comment by AyushSarode** [comment]
> scroll How is this?

Perfect!
Go for PR!

**Comment by AyushSarode** [comment]
Also Make sure to give star

**Pull request merged**
