### PR TITLE
Added Preloader

### PR DESCRIPTION
**Pull request by gaut2003**
Added Preloader.

### CODE REVIEW

**Comment by AyushSarode** [comment]
> Added Preloader.

The preloader looks big, please resize it and make it small.

Also When Preloader  is loading the website should not display-

**Comment by AyushSarode** [comment]
> > Added Preloader.
> 
> The preloader looks big, please resize it and make it small.
> 
> Also When Preloader is loading the website should not display-

**Comment by AyushSarode** [comment]
> > > Added Preloader.
> > 
> > 
> > Change the preloader I want different preloader. The preloader looks big, please resize it and make it small.
> > Also When Preloader is loading the website should not display-
> 
> Screenshot 2022-10-07 130822

**Comment by AyushSarode** [comment]
> > > > Added Preloader.
> > > 
> > > 
> > > Replace the Preloader. The preloader looks big, please resize it and make it small.
> > > Also When Preloader is loading the website should not display-
> > 
> > 
> > Screenshot 2022-10-07 130822

**Comment by AyushSarode** [comment]
> Kindly check I have done the needful changes.

Great efforts!
Satisfied with your work @gaut2003 .

**Comment by gaut2003** [comment]
Thank You Looking forward to contribute to your project further.

**Comment by AyushSarode** [comment]
> Thank You Looking forward to contribute to your project further.

Go ahead friend! 
Make sure to give a star on this repo. 
Thank you!

**Pull request merged**
