### PR TITLE
added prototype

### PR DESCRIPTION
**Pull request by AD1TYA03**
Initial commit added :-
1. Dark mode css
2. dark mode button

### CODE REVIEW

**Comment by AD1TYA03** [comment]
giving 2nd pr , with enabled button

**Comment by AD1TYA03** [comment]
@AyushSarode hey bro please merge this 

so that I can create other PR with everything done

**Comment by AyushSarode** [comment]
> 

1 Screenshot (4)

remove the bg of preloader

2 
Screenshot (5)

remove the white line above the dark mode

**Comment by AD1TYA03** [comment]
ok will work on it , That's why asked you to create new branch , you can merge into dark-mode branch I will fix these minor issues.

**Comment by AD1TYA03** [comment]
> ok will work on it , That's why asked you to create new branch , you can merge into dark-mode branch I will fix these minor issues.

@AyushSarode

**Comment by AyushSarode** [comment]
> ok will work on it , That's why asked you to create new branch , you can merge into dark-mode branch I will fix these minor issues.

Yup, I'm working on first issue, just work on 2nd one, I'll fix preloader!

**Comment by AyushSarode** [comment]
Working on it?

**Comment by AD1TYA03** [comment]
Sorry I am stuck on project myself for one of the hackthon , fix it yourself if you want , 

The problem is , hexcode is not updated on index.html , 
Only for body , hexcodes changes

Really sorry for that

**Comment by AyushSarode** [comment]
> Sorry I am stuck on project myself for one of the hackthon , fix it yourself if you want ,
> 
> The problem is , hexcode is not updated on index.html , Only for body , hexcodes changes
> 
> Really sorry for that

No problem, I'll fix it!
Thank you!

**Pull request closed without merging**
