### PR TITLE
Adding Search-bar and Changing some color on footer

### PR DESCRIPTION
**Pull request by Aniketmishra0**
Adding Search-bar and Changing some color on footer
Screenshot 2022-10-23 at 2 10 27 AM

### CODE REVIEW

**Comment by AyushSarode** [comment]
> Adding Search-bar and Changing some color on footer
> Screenshot 2022-10-23 at 2 10 27 AM
> 

Where is searchhar?

**Comment by Aniketmishra0** [comment]
See this screenshot 

Screenshot 2022-10-23 at 8 13 33 AM

**Comment by Aniketmishra0** [comment]
Screenshot 2022-10-23 at 8 13 33 AM

**Comment by AyushSarode** [comment]
No need to change footer Design.
Just move searchbar here - 
Capture

**Comment by Aniketmishra0** [comment]
@AyushSarode  
### Done 

Screenshot 2022-10-23 at 8 47 15 PM

**Comment by AyushSarode** [comment]
Leave footer as it is, I don't want any changes. Also when you scroll a bit that searchbar must be invisible.

**Review by Aniketmishra0 — COMMENTED** [review]
@AyushSarode as it is

**Pull request closed without merging**
