### PR TITLE
Navbar UI

### PR DESCRIPTION
**Pull request by Maryam-Momoh**
I improved on the Navbar UI

### CODE REVIEW

**Comment by AyushSarode** [comment]
> I improved on the Navbar UI
Don't add box, just add a simple line below each section of navbar

**Comment by Maryam-Momoh** [comment]
Okay, will do that

**Comment by AyushSarode** [comment]
It's not looking good

**Comment by AyushSarode** [comment]
I really appreciate your work.
Thank you!

**Comment by AyushSarode** [comment]
> > It's not looking good
> 
> can i work on it one more time?

This is my another repo, you can work on this issue if you want to.
https://github.com/AyushSarode/Social-media-buttons.github.io/issues/25

**Pull request closed without merging**
