### PR TITLE
Fixed the Footer

### PR DESCRIPTION
**Pull request by zugzwang03**
resolved issue #51 

Screenshots:

shared in issue #51

### CODE REVIEW

**Comment by zugzwang03** [comment]
Again the "hacktoberfest" tag problem 😆

**Comment by zugzwang03** [comment]
@AyushSarode

**Comment by AyushSarode** [comment]
> Again the "hacktoberfest" tag problem 😆

oh my..Sorry!

**Comment by zugzwang03** [comment]
So the tag must be "hacktoberfest-accepted", and not "hacktoberfest". 
Screenshot_20221020-232740_Chrome

**Comment by zugzwang03** [comment]
@AyushSarode

**Comment by AyushSarode** [comment]
Give some time to that website to reload.
It will track your progress.

**Pull request merged**
