### PR TITLE
Feature : Making links on side navbar hover with transition

### PR DESCRIPTION
**Pull request by MohitNamdev22**
Issue #53 
I've added a hover effect to the li links on the side navbar and transition.

https://user-images.githubusercontent.com/89779447/197011292-056e5f81-148b-441b-82a5-2eab8bc6af32.mp4

### CODE REVIEW

**Comment by AyushSarode** [comment]
> Issue #53 I've added a hover effect to the li links on the side navbar and transition.
> 
>  Learning.App.-.Google.Chrome.2022-10-20.22-22-13.mp4

Can you change that color, that blue color looks like default hyperlink color

**Comment by MohitNamdev22** [comment]
> > Issue #53 I've added a hover effect to the li links on the side navbar and transition.
> 
> > 
> 
> >  Learning.App.-.Google.Chrome.2022-10-20.22-22-13.mp4
> 
> 
> 
> Can you change that color, that blue color looks like default hyperlink color

Yes we can, can you suggest some?

**Comment by AyushSarode** [comment]
> > > Issue #53 I've added a hover effect to the li links on the side navbar and transition.
> > 
> > 
> > > 
> > 
> > 
> > > Learning.App.-.Google.Chrome.2022-10-20.22-22-13.mp4
> > 
> > 
> > Can you change that color, that blue color looks like default hyperlink color
> 
> Yes we can, can you suggest some?

okay so when I hover my cursor their it should be white and when it is in rest try this -#EDE4E0

**Comment by MohitNamdev22** [comment]
@AyushSarode Done the changes

**Comment by AyushSarode** [comment]
Instead of this #EDE4E0 can you add #FEFBF6

**Comment by AyushSarode** [comment]
> Sorry! 
Instead of this #EDE4E0 can you add #FEFBF6

**Comment by MohitNamdev22** [comment]
@AyushSarode what to do?

**Comment by AyushSarode** [comment]
> > Sorry!
> > Instead of this #EDE4E0 can you add #FEFBF6

That #EDE4E0 doesn't look good so change it.
Replace with #FEFBF6

**Comment by MohitNamdev22** [comment]
> > > Sorry!
> 
> > > Instead of this #EDE4E0 can you add #FEFBF6
> 
> 
> 
> That #EDE4E0 doesn't look good so change it.
> 
> Replace with #FEFBF6

But then that white color and fefbf6 both looking same

**Comment by AyushSarode** [comment]
> > > > Sorry!
> > 
> > 
> > > > Instead of this #EDE4E0 can you add #FEFBF6
> > 
> > 
> > That #EDE4E0 doesn't look good so change it.
> > Replace with #FEFBF6
> 
> But then that white color and fefbf6 both looking same

It's fine, I don't want any big change.

**Comment by MohitNamdev22** [comment]
@AyushSarode made the required changed

**Pull request merged**
